name: $ainews

permissions: write-all

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      env:
        MAM_COME: '0'
      with:
        package: 'ainews'
        modules: 'app' 
    
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'ainews/app/-' #FIXME path to build app
